CREATE TABLE WECHSEL(
    ID INT NOT NULL AUTO_INCREMENT,
    DATUM DATETIME DEFAULT CURRENT_TIMESTAMP, 
    QUELLKONTO VARCHAR(12) NOT NULL,
    ZIELKONTO VARCHAR(12) NOT NULL,
    BETRAG DECIMAL(20,2) DEFAULT 0,
    WECHSELKURS DECIMAL(10,2) DEFAULT 1,
    WAHRUNG INT DEFAULT 0,
    PRIMARY KEY(ID)
);
